### PR TITLE
added docstring for correlation function

### LINKED ISSUE #9: Skeleton Function 4: Correlation
- [ ] create skeleton of function to explore correlation of data with doc string

ideas include the correlation plot, identify values with high correlation over a threshold

### PR DESCRIPTION
**Pull request by sweber15**
Added docstring for correlation function Addressing issue #9

### CODE REVIEW

**Review by marvinmin — COMMENTED** [review]
Everything looks good. Except could you please change the term "numeric column" to "numeric variable"? I think the other docstrings all use "numeric variable".

**Comment by sweber15** [comment]
> Everything looks good. Except could you please change the term "numeric column" to "numeric variable"? I think the other docstrings all use "numeric variable".

Made the change in the docstring. Please review and let me know if you have any other changes.

**Review by marvinmin — APPROVED** [review]
Looks good!

**Review by sgauravm — APPROVED** [review]
Looks good !!

**Comment by sgauravm** [comment]
Changes looks good so merging it

**Pull request merged**
