### PR TITLE
Warpper function and describe_cat_var function docstring. Proposal in README. #7 #1

### LINKED ISSUE #1: Create README Proposal
- [ ] 	list of functions
- [ ] 	proposal and purpose

### LINKED ISSUE #7: Skeleton Function 2: Describe categorical values
- [ ] create skeleton of function to explore categorical variables with doc string

ideas include bar plot and count/proportion of variables

### LINKED ISSUE #16: Skeleton for wrapper function

### PR DESCRIPTION
**Pull request by sgauravm**

### CODE REVIEW

**Review by marvinmin — APPROVED** [review]
Looks great, thank you for writing the wrapper function!

**Review by sweber15 — COMMENTED** [review]
It looks good! The docstings are great!

There are some minor spelling errors in the README:

1. Remove `etc` in the second sentence and change "knowing `NA` values **and** plotting the distributions" 

2. "singe function" in the fourth sentence should be "single"

3. "Data" in the first sentence of Packaging positioning should be lowercase.

**Review by marvinmin — COMMENTED** [review]
I found the name of your function `describe_cat_variable` is different from the function name in README.

**Comment by sgauravm** [comment]
Corrected the spelling mistakes and moved functions under features header

**Pull request merged**
