### PR TITLE
initial project set up with cookiecutter and poetry

### PR DESCRIPTION
**Pull request by sweber15**
Reformat the repo with the cookiecutter template.  (Issue #4 )

### CODE REVIEW

**Review by v5y8 — COMMENTED** [review]
looks fine

**Review by v5y8 — APPROVED** [review]

**Review by marvinmin — APPROVED** [review]

**Review by sgauravm — APPROVED** [review]
Looks good.Merging it

**Comment by sgauravm** [comment]
What are these checks failed errors?

**Review by sgauravm — COMMENTED** [review]
I see 4 failure messages. Is that anything critical?

**Comment by sweber15** [comment]
> I see 4 failure messages. Is that anything critical?

They shouldn't be as they were with the style on the build process. Tiffany commented on someone comment on slack.

As per [the whole game document](https://ubc-mds.github.io/py-pkgs/whole-game.html):

"Note: It is very possible that your tests are correct and your function passes the tests yet the build button on the GitHub repository README still says “build: failing”. This is because the build continuous integration has more checks than just whether the tests pass, for example, it also checks code style using a tool called flake8. This and the other build checks are the subject of later chapters in this book."

**Review by sgauravm — APPROVED** [review]
looks good. Merging it

**Pull request merged**
